#
# Configuration File
#

[general]
n_testers = 52
n_valid_testers = 46
n_questions = 24
reduced_test_users = [25, 26, 30]
excluded_users = [5, 23, 25, 26, 30, 50]

[path]
brainwaves_folder = './datasets/eeg'
solutions_complete_dataset = './datasets/questions/solutions_complete.csv'
answers_complete_dataset = './datasets/questions/answers_complete.csv'
labelled_dataset = './datasets/results/labels/labelled_dataset.csv'
sync_prefix = '/datasets/sync_datasets/norm_1_1/'

[algorithm]
eeg_features = ['alpha1', 'alpha2', 'beta1', 'beta2', 'delta']
gaze_features = ['FPOGX', 'FPOGY', 'FPOGV', 'RPD', 'LPD']
n_cnn_filters = [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
cnn_kernel_size = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
n_lstm_units = [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
activation_types = ['relu', 'tanh', 'leaky_relu', 'para_relu', 'elu', 'linear']

[preprocessing]
min_normalization = -1
max_normalization  = 1
interpolation_kind = 'linear'
sync_normalization = true
resample_library = 'scipy'