#
# Configuration File
#

[general]
n_testers = 52
n_valid_testers = 46
n_questions = 24
reduced_test_users = [25, 26, 30]
excluded_users = [5, 23, 25, 26, 30, 50]

[path]
brainwaves_folder = './datasets/eeg'
solutions_complete_dataset = './datasets/questions/solutions_complete.csv'
answers_complete_dataset = './datasets/questions/answers_complete.csv'
labelled_dataset = './datasets/results/labels/labelled_dataset.csv'
# sync_prefix = './datasets/sync_datasets/no_norm/'
sync_prefix = './test/'

[algorithm]
eeg_features = ['alpha1', 'alpha2', 'beta1', 'beta2', 'delta']
gaze_features = ['FPOGX', 'FPOGY', 'FPOGD', 'RPD', 'LPD']

[preprocessing]
min_normalization = -1
max_normalization  = 1
interpolation_kind = 'linear'
sync_normalization = false
resample_library = 'scipy'