#
# Configuration File
#

[general]
n_testers = 51
reduced_test_users = [25, 26, 30]
excluded_users = [25, 26, 30]

[path]
brainwaves_folder = './datasets/eeg'
solutions_complete_dataset = './datasets/questions/solutions_complete.csv'
answers_complete_dataset = './datasets/questions/answers_complete.csv'