#
# Configuration File
#

[general]
n_testers = 52
n_valid_testers = 46
n_questions = 24
reduced_test_users = [25, 26, 30]
excluded_users = [5, 23, 25, 26, 30, 50]
binary_value = [0] # 0, 1

[path]
brainwaves_folder = './datasets/eeg'
solutions_complete_dataset = './datasets/questions/solutions_complete.csv'
answers_complete_dataset = './datasets/questions/answers_complete.csv'
labelled_dataset = './datasets/results/labels/labelled_dataset.csv'
sync_prefix = 'datasets/sync_datasets/complete/norm_1_1/'

input_arrays = ['datasets/arrays/complete/input_1_1_complete_no_fpogv.npy']

labels_arrays = ['datasets/arrays/labels/labels_v2.npy'
] # 'datasets/arrays/labels/labels_v2_2F.npy'

[algorithm]
eeg_features = ['alpha1', 'alpha2', 'beta1', 'beta2', 'delta']
gaze_features = ['FPOGX', 'FPOGY', 'RPD', 'LPD'] # 'FPOGV' (test come maschera)
fpogv_mask = ['FPOGV']
n_cnn_filters = [256] # 512, 1024
cnn_kernel_size = [8] # 4, 8, 10
cnn_pool_size = [4] # 2, 4, 8
n_lstm_units = [64] # 32, 64, 128
dropout_value = [0.2] # 0.1, 0.2, 0.5
dense_input_dim = [39684] # 19842
activation_types = ['relu'] # linear, softmax
loss_types = ['mean_squared_error']
optimizer_types = ['adam'] # 'SGD', 'Ftrl', 'Adadmax'
# activation_types = ['relu', 'tanh', 'leaky_relu', 'para_relu', 'elu', 'linear']
# loss_types = ['mean_squared_error', 'mean_absolute_error', 'cosine_similarity', 'binary_crossentropy', 'categorical_crossentropy', 'poisson', 'sparse_categorical_crossentropy', 'hinge']
# optimizer_types = ['adam', 'SGD', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl']

[preprocessing]
min_normalization = -1
max_normalization  = 1
interpolation_kind = 'linear'
sync_normalization = true
resample_library = 'scipy'

[computed]
shifted_max_len = 2646