#
# Configuration File
#

[general]
n_testers = 52
n_questions = 24
reduced_test_users = [25, 26, 30]
excluded_users = [5, 23, 25, 26, 30, 50]

[path]
brainwaves_folder = './datasets/eeg'
solutions_complete_dataset = './datasets/questions/solutions_complete.csv'
answers_complete_dataset = './datasets/questions/answers_complete.csv'