#
# Configuration File
#

[general]
n_testers = 52
n_valid_testers = 46
n_questions = 24
reduced_test_users = [25, 26, 30]
not_valid_users = [5, 23, 25, 26, 30, 50]
excluded_users = [5, 23, 25, 26, 30, 50, 1, 10, 20, 35, 40]
validation_users = [1, 10, 20, 35, 40]
binary_value = [0, 1]

[path]
brainwaves_folder = './datasets/eeg'
solutions_complete_dataset = './datasets/questions/solutions_complete.csv'
answers_complete_dataset = './datasets/questions/answers_complete.csv'
labelled_dataset = './datasets/results/labels/labelled_dataset_v2.csv'
sync_prefix = 'datasets/sync_datasets/undersampled/norm_1_1/'
sync_validation_prefix = 'datasets/sync_datasets/undersampled/norm_1_1/'
filename_results = 'results.csv'
filename_performances_cross_corr = 'perfomances_cross.csv'
filename_performances_aggregate = 'performances_aggr.csv'


input_arrays = ['datasets/arrays/undersampled_shifted/input_1_1.npy']
labels_arrays = ['datasets/arrays/labels/labels_v2.npy']

[random_seed]
pythonhashseed = 2022
python_seed = 2022
numpy_seed = 2022 # same as scipy seed
tf_seed = 2022
keras_seed = 2022

[algorithm]
eeg_features = ['alpha1', 'alpha2', 'beta1', 'beta2', 'delta']
gaze_features = ['FPOGX', 'FPOGY', 'RPD', 'LPD'] # 'FPOGV' (test come maschera)
fpogv_mask = ['FPOGV']
test_size = 0.20 # 0.13
min_len_thr = 20
n_kfold_splits = 5
n_cnn_filters = [256] # 512, 1024
cnn_kernel_size = [8] # 4, 8, 10
cnn_pool_size = [4] # 2, 4, 8
n_lstm_units = [64] # 32, 64, 128
dropout_value = [0.2] # 0.1, 0.2, 0.5
dense_input_dim = [177] # 2646, half
activation_types = ['relu'] # linear, softmax
loss_types = ['mean_squared_error']
optimizer_types = ['adam'] # 'SGD', 'Ftrl', 'Adadmax'
# activation_types = ['relu', 'tanh', 'leaky_relu', 'para_relu', 'elu', 'linear']
# loss_types = ['mean_squared_error', 'mean_absolute_error', 'cosine_similarity', 'binary_crossentropy', 'categorical_crossentropy', 'poisson', 'sparse_categorical_crossentropy', 'hinge']
# optimizer_types = ['adam', 'SGD', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl']

[preprocessing]
min_normalization = -1
max_normalization  = 1
interpolation_kind = 'linear'
sync_normalization = true
resample_library = 'scipy'

[computed]
shifted_max_len = 2646