import statistics.utilities
import pandas as pd

df_complete = pd.read_csv('datasets/results/answers_complete_all_info.csv')

answer_dict = statistics.utilities.get_times_dict(df_complete, 'MEDIA_NAME')
min_answer_dict = statistics.utilities.get_min_right_dict(df_complete, 'MEDIA_NAME')
mean_answer_dict = statistics.utilities.get_mean_dict(answer_dict)
median_answer_dict = statistics.utilities.get_median_dict(answer_dict)
df_answers_labelled_mean = statistics.set_labels.get_df_answers_labelled(df_complete, min_answer_dict, mean_answer_dict, 'MEDIA_NAME')
df_answers_labelled_median = statistics.set_labels.get_df_answers_labelled(df_complete, min_answer_dict, median_answer_dict, 'MEDIA_NAME')
df_labelled_mean_answer_statistics = statistics.set_labels.get_df_label_statistics(df_answers_labelled_mean, 'MEDIA_NAME')
df_labelled_median_answer_statistics = statistics.set_labels.get_df_label_statistics(df_answers_labelled_median, 'MEDIA_NAME')
df_answers_labelled_mean.to_csv('datasets/results/labels/mean/labels_mean_answers_all_info.csv', index=False)
df_answers_labelled_median.to_csv('datasets/results/labels/median/labels_median_answers_all_info.csv', index=False)
df_labelled_mean_answer_statistics.to_csv('datasets/results/labels/statistic/labels_mean_statistics_answers_all_info.csv', index=False)
df_labelled_median_answer_statistics.to_csv('datasets/results/labels/statistic/labels_median_statistics_answers_all_info.csv', index=False)

specific_categories_dict = statistics.utilities.get_times_dict(df_complete, 'SPECIFIC_CATEGORY')
min_specific_categories_dict = statistics.utilities.get_min_right_dict(df_complete, 'SPECIFIC_CATEGORY')
mean_specific_categories_dict = statistics.utilities.get_mean_dict(specific_categories_dict)
median_specific_categories_dict = statistics.utilities.get_median_dict(specific_categories_dict)
df_specific_categories_labelled_mean = statistics.set_labels.get_df_answers_labelled(df_complete, min_specific_categories_dict, mean_specific_categories_dict, 'SPECIFIC_CATEGORY')
df_specific_categories_labelled_median = statistics.set_labels.get_df_answers_labelled(df_complete, min_specific_categories_dict, median_specific_categories_dict, 'SPECIFIC_CATEGORY')
df_labelled_specific_categories_mean_statistics = statistics.set_labels.get_df_label_statistics(df_specific_categories_labelled_mean, 'SPECIFIC_CATEGORY')
df_labelled_specific_categories_median_statistics = statistics.set_labels.get_df_label_statistics(df_specific_categories_labelled_median, 'SPECIFIC_CATEGORY')
df_specific_categories_labelled_mean.to_csv('datasets/results/labels/mean/labels_mean_specific_categories_all_info.csv', index=False)
df_specific_categories_labelled_median.to_csv('datasets/results/labels/median/labels_median_specific_categories_all_info.csv', index=False)
df_labelled_specific_categories_mean_statistics.to_csv('datasets/results/labels/statistic/labels_mean_statistics_specific_categories_all_info.csv', index=False)
df_labelled_specific_categories_median_statistics.to_csv('datasets/results/labels/statistic/labels_median_statistics_specific_categories_all_info.csv', index=False)

macro_categories_dict = statistics.utilities.get_times_dict(df_complete, 'MACRO_CATEGORY')
min_macro_categories_dict = statistics.utilities.get_min_right_dict(df_complete, 'MACRO_CATEGORY')
mean_macro_categories_dict = statistics.utilities.get_mean_dict(macro_categories_dict)
median_macro_categories_dict = statistics.utilities.get_median_dict(macro_categories_dict)
df_macro_categories_labelled_mean = statistics.set_labels.get_df_answers_labelled(df_complete, min_macro_categories_dict, mean_macro_categories_dict, 'MACRO_CATEGORY')
df_macro_categories_labelled_median = statistics.set_labels.get_df_answers_labelled(df_complete, min_macro_categories_dict, median_macro_categories_dict, 'MACRO_CATEGORY')
df_labelled_macro_categories_mean_statistics = statistics.set_labels.get_df_label_statistics(df_macro_categories_labelled_mean, 'MACRO_CATEGORY')
df_labelled_macro_categories_median_statistics = statistics.set_labels.get_df_label_statistics(df_macro_categories_labelled_median, 'MACRO_CATEGORY')
df_macro_categories_labelled_mean.to_csv('datasets/results/labels/mean/labels_mean_macro_categories_all_info.csv', index=False)
df_macro_categories_labelled_median.to_csv('datasets/results/labels/median/labels_median_macro_categories_all_info.csv', index=False)
df_labelled_macro_categories_mean_statistics.to_csv('datasets/results/labels/statistic/labels_mean_statistics_macro_categories_all_info.csv', index=False)
df_labelled_macro_categories_median_statistics.to_csv('datasets/results/labels/statistic/labels_median_statistics_macro_categories_all_info.csv', index=False)
